name: CI

on: 
  push:
    branches:    
      - fanyinghao/develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build with xgo
      uses: crazy-max/ghaction-xgo@v1.0.0
      with:
        go_version: 1.13.3
        dest: build
        prefix: openw-cli
        targets: darwin/amd64
        v: true
        x: true
        ldflags: -s -w
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: openw-cli-artifacts
        path: build