name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build with xgo
      uses: crazy-max/ghaction-xgo@0.3.0
      with:
        go_version: 1.12.4
        dest: build
        prefix: openw-cli
        targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
        v: true
        x: true
        ldflags: -s -w
    - name: Github Release
      uses: elgohr/Github-Release-Action@1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REF: ${{ GITHUB_REF }}
      with:
        args: $GITHUB_REF
